package com.cqupt.pojo;

public class Tbuser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbuser.userid
     *
     * @mbg.generated Mon Aug 02 15:16:12 GMT+08:00 2021
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbuser.username
     *
     * @mbg.generated Mon Aug 02 15:16:12 GMT+08:00 2021
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbuser.userpwd
     *
     * @mbg.generated Mon Aug 02 15:16:12 GMT+08:00 2021
     */
    private String userpwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbuser.phone
     *
     * @mbg.generated Mon Aug 02 15:16:12 GMT+08:00 2021
     */
    private String phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbuser.userid
     *
     * @return the value of tbuser.userid
     *
     * @mbg.generated Mon Aug 02 15:16:12 GMT+08:00 2021
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbuser.userid
     *
     * @param userid the value for tbuser.userid
     *
     * @mbg.generated Mon Aug 02 15:16:12 GMT+08:00 2021
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbuser.username
     *
     * @return the value of tbuser.username
     *
     * @mbg.generated Mon Aug 02 15:16:12 GMT+08:00 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbuser.username
     *
     * @param username the value for tbuser.username
     *
     * @mbg.generated Mon Aug 02 15:16:12 GMT+08:00 2021
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbuser.userpwd
     *
     * @return the value of tbuser.userpwd
     *
     * @mbg.generated Mon Aug 02 15:16:12 GMT+08:00 2021
     */
    public String getUserpwd() {
        return userpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbuser.userpwd
     *
     * @param userpwd the value for tbuser.userpwd
     *
     * @mbg.generated Mon Aug 02 15:16:12 GMT+08:00 2021
     */
    public void setUserpwd(String userpwd) {
        this.userpwd = userpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbuser.phone
     *
     * @return the value of tbuser.phone
     *
     * @mbg.generated Mon Aug 02 15:16:12 GMT+08:00 2021
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbuser.phone
     *
     * @param phone the value for tbuser.phone
     *
     * @mbg.generated Mon Aug 02 15:16:12 GMT+08:00 2021
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }
}