package com.cqupt.dao;

import com.cqupt.pojo.Tbuser;
import com.cqupt.pojo.TbuserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbuser
     *
     * @mbg.generated Mon Aug 02 15:16:12 GMT+08:00 2021
     */
    long countByExample(TbuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbuser
     *
     * @mbg.generated Mon Aug 02 15:16:12 GMT+08:00 2021
     */
    int deleteByExample(TbuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbuser
     *
     * @mbg.generated Mon Aug 02 15:16:12 GMT+08:00 2021
     */
    int deleteByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbuser
     *
     * @mbg.generated Mon Aug 02 15:16:12 GMT+08:00 2021
     */
    int insert(Tbuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbuser
     *
     * @mbg.generated Mon Aug 02 15:16:12 GMT+08:00 2021
     */
    int insertSelective(Tbuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbuser
     *
     * @mbg.generated Mon Aug 02 15:16:12 GMT+08:00 2021
     */
    List<Tbuser> selectByExample(TbuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbuser
     *
     * @mbg.generated Mon Aug 02 15:16:12 GMT+08:00 2021
     */
    Tbuser selectByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbuser
     *
     * @mbg.generated Mon Aug 02 15:16:12 GMT+08:00 2021
     */
    int updateByExampleSelective(@Param("record") Tbuser record, @Param("example") TbuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbuser
     *
     * @mbg.generated Mon Aug 02 15:16:12 GMT+08:00 2021
     */
    int updateByExample(@Param("record") Tbuser record, @Param("example") TbuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbuser
     *
     * @mbg.generated Mon Aug 02 15:16:12 GMT+08:00 2021
     */
    int updateByPrimaryKeySelective(Tbuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbuser
     *
     * @mbg.generated Mon Aug 02 15:16:12 GMT+08:00 2021
     */
    int updateByPrimaryKey(Tbuser record);
}